### ISSUE TITLE
could we give the access to each user with the table?

### ISSUE THREAD

**Issue by xinhuiwang** [ada-discovery/ada-issues#190] opened 2021-08-11 08:11 UTC
I am giving access to each user on different projects. I have to give one-to-one or copy the access. I am just wondering could we have a table with the column as projects and rows as projects, and I could see the access and give the access very easily.  or I could define some groups and give the access?

**Comment by sherzinger** [comment] 2021-08-23 08:50
duplicate of #177

**Closed as completed by sherzinger** 2021-08-23 08:50 UTC
